services:
  caddy:
    container_name: caddy
    image: caddy:2.10-alpine
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/infra/caddy/Caddyfile:/etc/caddy/Caddyfile
  app:
    container_name: app
    image: ghcr.io/maxbesley/fresh-app
    ports:
      - 9000:9000
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 120 --cleanup

volumes:
  caddy_data:
  caddy_config:
